Resolve resize issue under Qt 6 environment.
BLumia/pineapple-pictures pull request #81
Opened 2023-03-25 08:02 UTC by yyc12345

Qt 6 assume that `Qt::WindowMinMaxButtonsHint` depend on `Qt::WindowSystemMenuHint`. And hard-code this in its source code. Source code reference: https://github.com/qt/qtbase/blob/6.4.2/src/plugins/platforms/windows/qwindowswindow.cpp#L833

However, if `Qt::WindowSystemMenuHint` added, an extra window style called `WS_SYSMENU` will be added for this frameless window. Due to Windows implementation, if `WS_SYSMENU` existed, any resize operations of this window will fail, even `QWidget::nativeEvent()` was still running. 

I have tried `QWidget::setWindowFlag(Qt::WindowSystemMenuHint, false);` but it doesn't work. Obviously, we can remove `Qt::WindowMinMaxButtonsHint` to solve this issue. But we can not click icon on taskbar to minimize this window if removing it. This breaks the experience of this app, then I gave this up. 

So this is the final solution. I use native Win32 API to forced remove this annoying flag.

2023-03-25 08:34 UTC, BLumia commented on app/framelesswindow.cpp
> +    {
```suggestion
    if (flags != 0) {
```

2023-03-25 08:59 UTC, BLumia approved these changes

2023-03-25 14:49 UTC, BLumia requested changes
Seems it is indeed caused by the `WS_SYSMENU` window flag, but the fix doesn't seem to be working as intended. The transparency was lost once this patch get applied, and there is also a `setWindowFlag()` call in `MainWindow` which can cause the `WS_SYSMENU` to be set on again by Qt internal.

Another solution is... simply remove `Qt::WindowMinMaxButtonsHint` from window flags list, but then <kbd>Winkey+Up</kbd> / <kbd>Winkey+Down</kbd> will likely no longer works, and user will also no longer be able to minimize the window by clicking the taskbar icon.

2023-04-16 12:06 UTC, BLumia commented
> Another solution is... simply remove `Qt::WindowMinMaxButtonsHint` from window flags list, but then Winkey+Up / Winkey+Down will likely no longer works, and user will also no longer be able to minimize the window by clicking the taskbar icon.

I updated the master branch code with this as a workaround change before the real fix comes out.

2023-06-23 16:04 UTC, yyc12345 commented
that's all what i have done.
hope you can check it out, especially code format and memory issue.
the references of this implementation already has been written in code file.

2023-06-23 16:49 UTC, BLumia reviewed
About code style, please follow Qt's coding style for newly added code, see https://wiki.qt.io/Qt_Coding_Style#Braces

TODO:

- [x] Check if Windows + Qt 5 version works (CI build is fine)
- [ ] Check if Windows + Qt 6 version works (CI build is fine)
- [ ] Check if Linux + Qt 5 version works (manually)
- [ ] Check if Linux + Qt 6 version works (manually)

2023-06-23 16:49 UTC, BLumia commented on app/framelesswindow.cpp
> +    }
```suggestion
    case QEvent::MouseButtonPress:
        return mousePress(static_cast<QMouseEvent*>(e));
```

2023-06-24 05:10 UTC, BLumia reviewed
Some minor issues, over all looks good to me :)

2023-06-24 05:10 UTC, BLumia commented on app/framelesswindow.cpp
>  #include <windows.h>
We can remove this now :)

2023-06-24 05:10 UTC, BLumia commented on app/framelesswindow.cpp
>      // Thanks @yyc12345 for finding out the source of the issue.
This can be removed too.

2023-06-24 05:27 UTC, BLumia approved these changes

2023-06-24 06:37 UTC, merged